#!/bin/sh

date=$(date '+%Y-%m-%d')
time=$(date '+%H:%M')
dir=~/Notes/neorg/diary
file=$dir/$date.norg

[ -f $dir ] ||
    mkdir -p $dir

swaymsg fullscreen enable
echo -e "\n* $time\n" >> $file
nvim "$file" +'set linebreak wrap' +ZenMode +startinsert +'set nonu nornu scl=no' +

