#!/usr/bin/env bash

tool=$1

wallpaper=$(sxiv -o -r ~/wallpapers/)
cp "$wallpaper" ~/wallpapers/wallpaper.jpg
session_type=$XDG_SESSION_TYPE

if [ "$session_type" != "wayland" ]; then
    if [ "$tool" == "wal" ]; then
        echo "setting \"$wallpaper\" as wallpaper with wal"
        wal -i "$wallpaper"
    else
        echo "setting \"$wallpaper\" as wallpaper with feh"
        feh --bg-fill "$wallpaper"
    fi
else
    echo "setting \"$wallpaper\" as wallpaper"
    if [[ "$wallpaper" =~ "/bw/" ]]; then
        pkill swaybg ; swaybg -m center -o "*" -i "$wallpaper" -c "#1a1a1a" &
    else
        pkill swaybg ; swaybg -m fill -o "*" -i "$wallpaper" -c "#1a1a1a" &
    fi
fi
