#! /bin/sh

action=$1

case $action in
    "up")
        wpctl set-volume @DEFAULT_SINK@ 5%+
        ;;
    "down")
        wpctl set-volume @DEFAULT_SINK@ 5%-
        ;;
    "toggle")
        wpctl set-mute @DEFAULT_SINK@ toggle
        ;;
    "mic")
        # pamixer --default-source -t
        # [[ "$(pamixer --default-source --get-mute)" == "true" ]] &&
        #     notify-send -t 1000 "Microphone off" ||
        #     notify-send -t 1000 "Microphone on"
        # exit
        ;;
esac

volume=`wpctl get-volume @DEFAULT_SINK@ | tr ' ' '\n' | grep '0\.[0-9]' | cut -d '.' -f 2`
description=`wpctl inspect @DEFAULT_SINK@ | grep node.description | cut -d '"' -f 2`
muted=`wpctl get-volume @DEFAULT_SINK@ | grep muted -io | tr '[:upper:]' '[:lower:]'`

if [ $muted = 'muted' ]; then
    notify-send -t 1000 -h int:value:"$volume" "Volume (muted)" "$description" -a "Volume script"
else
    notify-send -t 1000 -h int:value:"$volume" "Volume" "$description" -a "Volume script"
fi
